version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:17.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "dependecies"
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
      docker:
        - image: cimg/node:17.8.0
      steps:
        - checkout
        - restore_cache: 
            keys:
              - "dependecies"
        - run: npm i
        - run: npm run test

  analyze:
      docker:
        - image: cimg/node:17.8.0
      steps:
        - checkout
        - restore_cache: 
            keys:
              - "dependecies"
        - run: npm i
        - run: npm audit

workflows:
  say-hello-workflow:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - analyze: 
          requires:
            - test
        
